apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-exporter
  template:
    metadata:
      labels:
        app: custom-exporter
    spec:
      containers:
      - name: custom-exporter
        image: ttl.sh/exporter-demo:1h
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: custom-exporter
  labels:
    app: custom-exporter
  annotations:
    prometheus.io/port: "web"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: custom-exporter
  ports:
  - name: web
    port: 8080

